project:
  type: website

website:
  title: "project-tracker"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - get-project.md
      - review-data.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



